# Generated by Django 4.2.3 on 2023-07-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_photo_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
